version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:22.14

commands:
  setup_npm_auth:
    steps:
      - run:
          name: Setup NPM auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_npm_auth
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install JUnit coverage reporter
          command: npm install --no-save jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: npx jest --coverage --ci --maxWorkers=1 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_npm_auth
      - run:
          name: Install
          command: npm install
      - run:
          name: Release
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            npx semantic-release

workflows:
  version: 2
  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
            - prodsec-orb-runtime
          channel: alerts-app-sec
          trusted-branch: master
          filters:
            branches:
              ignore:
                - master    
      - test:
          name: Test
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
  release:
    jobs:
      - release:
          name: Release
          context:
            - nodejs-install
            - github-release
          filters:
            branches:
              only:
                - master
